### ISSUE TITLE
singularity question

### ISSUE THREAD

**Issue by pandamzzzzz** [venturi123/DRLinFluids#12]
i use singularity exec command to calculate

when i run the cylinder2D_multiprocessing example, it has finished the follow step:

OpenFOAM_init running time： 2.67 s
OpenFOAM_init running time： 2.39 s
OpenFOAM_init running time： 2.49 s
OpenFOAM_init running time： 2.43 s
OpenFOAM_init running time： 2.43 s
WARNING:root:No min_value bound specified for state.
Agent defined DONE!
Runner defined DONE!
Episodes:   0%|  

and start run but it show up this message in log :

 System call: open(2)
 Error:       Permission denied (errno 13)

i think this maybe the problem of opening file?

**Comment by venturi123** [comment]
Hi @pandamzzzzz ,

Could you please show me more context printed on your terminal about this error? Besides, are you working on WSL or HPC cluster?

Also, have you ever try to use `singularity shell` mode to run the example?

**Comment by pandamzzzzz** [comment]
Hi @venturi123，
Thanks for your replyment, i work on HPC cluster so i need to use a slurm script to run the example. I will try singularity shell mode to run

**Comment by pandamzzzzz** [comment]
the more detail of error information are shown in follow message when use singularity exec mode

WARNING:root:No min_value bound specified for state.

Episodes:   0%|          | 0/3000 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%, comm=0.0%]
Episodes:   0%|          | 1/3000 [09:00, reward=0.00, ts/ep=100, sec/ep=540.89, ms/ts=5408.9, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 2/3000 [17:57, reward=-6.50, ts/ep=100, sec/ep=536.41, ms/ts=5364.1, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 3/3000 [26:53, reward=-6.50, ts/ep=100, sec/ep=535.93, ms/ts=5359.3, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 4/3000 [35:50, reward=-6.50, ts/ep=100, sec/ep=536.79, ms/ts=5367.9, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 5/3000 [44:47, reward=-6.50, ts/ep=100, sec/ep=537.95, ms/ts=5379.5, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 6/3000 [53:46, reward=-6.50, ts/ep=100, sec/ep=538.03, ms/ts=5380.3, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 7/3000 [1:02:41, reward=-6.50, ts/ep=100, sec/ep=535.97, ms/ts=5359.7, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 8/3000 [1:11:40, reward=-6.50, ts/ep=100, sec/ep=538.77, ms/ts=5387.7, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 9/3000 [1:20:34, reward=-6.50, ts/ep=100, sec/ep=533.95, ms/ts=5339.5, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 10/3000 [1:29:30, reward=-6.50, ts/ep=100, sec/ep=536.14, ms/ts=5361.4, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 11/3000 [1:38:29, reward=-6.50, ts/ep=100, sec/ep=538.51, ms/ts=5385.1, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 12/3000 [1:47:22, reward=-6.50, ts/ep=100, sec/ep=533.33, ms/ts=5333.3, agent=0.1%, comm=0.0%]--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  compute01
  System call: open(2) 
  Error:       Permission denied (errno 13)
--------------------------------------------------------------------------
[compute01:420949] 4 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
[compute01:420949] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

Episodes:   0%|          | 13/3000 [1:56:16, reward=-6.50, ts/ep=100, sec/ep=534.13, ms/ts=5341.3, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 14/3000 [2:05:10, reward=-6.50, ts/ep=100, sec/ep=533.57, ms/ts=5335.7, agent=0.1%, comm=0.0%]
Episodes:   0%|          | 15/3000 [2:14:03, reward=-6.50, ts/ep=100, sec/ep=533.07, ms/ts=5330.7, agent=0.1%, comm=0.0%]
Episodes:   1%|          | 16/3000 [2:23:05, reward=-6.50, ts/ep=100, sec/ep=541.63, ms/ts=5416.3, agent=0.1%, comm=0.0%]
Episodes:   1%|          | 17/3000 [2:32:03, reward=-6.50, ts/ep=100, sec/ep=538.74, ms/ts=5387.4, agent=0.1%, comm=0.0%]
Episodes:   1%|          | 18/3000 [2:41:01, reward=-6.50, ts/ep=100, sec/ep=537.95, ms/ts=5379.5, agent=0.1%, comm=0.0%]

**Comment by venturi123** [comment]
Hi @pandamzzzzz ,

DRLinFluids has been well tested on general Linux systems. However, it lacks extensive testing on multi-node HPC clusters. I have noticed that there are indeed some issues occurring on specific HPC platforms. I will report them as bugs and work on fixing them soon.

Thanks for your report. : )

**Comment by zonexo** [comment]
Hi,

I got this error running on HPC:

```
(DRLinFluids) Singularity> python3 DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py
OpenFOAM_init running time： 7.01 s
WARNING:root:No min_value bound specified for state.
Traceback (most recent call last):
  File "DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py", line 113, in <module>
    agent = Agent.create(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 104, in create
    return Agent.create(agent=agent, environment=environment)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 71, in create
    agent.initialize()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 263, in initialize
    self.model.initialize()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/models/tensorforce.py", line 503, in initialize
    super().initialize()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/models/model.py", line 295, in initialize
    self.initialize_api()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/models/tensorforce.py", line 611, in initialize_api
    super().initialize_api()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/models/model.py", line 347, in initialize_api
    self.act(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/module.py", line 128, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/module.py", line 112, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/models/model.py", line 570, in act
    actions, internals = self.core_act(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/module.py", line 128, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/module.py", line 112, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/models/tensorforce.py", line 960, in core_act
    lengths = tf_util.ones(shape=(batch_size,), dtype='int')
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/core/utils/tf_util.py", line 94, in ones
    return tf.ones(shape=shape, dtype=get_dtype(type=dtype))
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 3041, in ones
    output = _constant_if_small(one, shape, dtype, name)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2732, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/home/svu/tsltaywb/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/home/svu/tsltaywb/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 845, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (agent/Cast:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

Can you help?
