### ISSUE TITLE
Problem with ./wmakeall

### ISSUE THREAD

**Issue by CharAaznable** [venturi123/DRLinFluids#13]
Hi. I am using DRLinFluids in HPC.

When I followed the instructions to run the examples, I found some error with running **_./wmakeall_**.

Below is the information from terminal.
```(DRLinFluids) Singularity> ./wmakeall
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/incrementalJetParabolicVelocityFvPatchVectorField.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementalJetParabolicVelocity.so
/usr/bin/ld.bfd: cannot open output file /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementalJetParabolicVelocity.so: Read-only file system
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:169: /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementalJetParabolicVelocity.so] Error 1
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/incrementalJetUniVelocityFvPatchVectorField.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementalJetUniVelocity.so
/usr/bin/ld.bfd: cannot open output file /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementalJetUniVelocity.so: Read-only file system
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:169: /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementalJetUniVelocity.so] Error 1
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/inletParabolicVelocityFvPatchVectorField.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libinletParabolicVelocity.so
/usr/bin/ld.bfd: cannot open output file /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libinletParabolicVelocity.so: Read-only file system
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:169: /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libinletParabolicVelocity.so] Error 1
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/incrementallinearJetUniVelocityFvPatchVectorField.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementallinearJetUniVelocity.so
/usr/bin/ld.bfd: cannot open output file /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementallinearJetUniVelocity.so: Read-only file system
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:169: /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementallinearJetUniVelocity.so] Error 1
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/incrementallinearJetParabolicVelocityFvPatchVectorField.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementallinearJetParabolicVelocity.so
/usr/bin/ld.bfd: cannot open output file /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementallinearJetParabolicVelocity.so: Read-only file system
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:169: /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libincrementallinearJetParabolicVelocity.so] Error 1
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/jetParabolicVelocityFvPatchVectorField.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libjetParabolicVelocity.so
/usr/bin/ld.bfd: cannot open output file /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libjetParabolicVelocity.so: Read-only file system
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:169: /opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/libjetParabolicVelocity.so] Error 1
```
After that, I continued to try an example and it returned an error.

```
(DRLinFluids) Singularity> python launch_multiprocessing_traning_square.py
Traceback (most recent call last):
  File "launch_multiprocessing_traning_square.py", line 366, in <module>
    test_sac_with_il()
  File "launch_multiprocessing_traning_square.py", line 158, in test_sac_with_il
    foam_root_path=env_path_list[0],
IndexError: list index out of range
```

**Comment by venturi123** [comment]
Hi @CharAaznable ,

DRLinFluids has been well tested on general Linux systems. However, it lacks extensive testing on multi-node HPC clusters. I have noticed that there are indeed some issues occurring on specific HPC platforms (#12) . This will be reported as bugs. 

It may take some time but I will work on fixing them as soon as possible.

Thanks for your report. : )

**Comment by CharAaznable** [comment]
Hello. @venturi123 

Thank you for your reply.

Recently, I changed into another HPC cluster and installed DRLinFluids by **_tar.gz_** file.
After that, I run ``
./wmakell
`` and the HPC made it.
However, when I test the example in``
cylinder2D_multiprocessing
``, it showed some error which is shown below.
```
(DRLinFluids) e1192412@atlas9-c01:/home/DRLinFluids-0.1.1/examples/cylinder2D_multiprocessing/DRLinFluids_cylinder$ python launch_multiprocessing_traning_cylinder.py
Traceback (most recent call last):
  File "launch_multiprocessing_traning_cylinder.py", line 99, in <module>
    evaluation_environment = environments.pop()
IndexError: pop from empty list
``` 

Thanks.
